name: Hourly Update v2

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v4 # 升级到 v4
      - name: Set up Python
        uses: actions/setup-python@v5 # 升级到 v5
        with:
          python-version: '3.11' # 用更稳的 3.11
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python watchman_v2.py
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Security patch: Upgrade Actions & Update data" || exit 0
          git push
