name: Hourly Update v2

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行
  workflow_dispatch:      # 允许手动运行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 赋予机器人修改文件的权限
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python watchman_v2.py
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update weather & picnic advice" || exit 0
          git push
